[package]
name = "casec"
version = "0.1.1"
authors = ["Mateusz Szczygiel <mateuszszczygiel95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.3"
structopt = "0.3.13"
